server:
  port: 8080

flask:
  url: http://localhost:5000/extraction

# s3
cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

    s3:
      bucket: llmeta-be-bucket

    stack:
      auto: false

    region:
      static: ap-northeast-2

spring:
  config:
    activate:
      on-profile: dev

  servlet:
    session:
      cookie:
        path: /
        http-only: false
        max-age: P7D

    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://llmeta-database.cxn9oybwo8mo.ap-northeast-2.rds.amazonaws.com:3306/llmeta?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: admin
    password: llmeta2024
    driver-class-name: com.mysql.cj.jdbc.Driver

springdoc:
  api-docs:
    path: /api-docs
    group:
      enable: true

  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none

#  cache:
#    disabled: true

  model-and-view-allowed: true