spring:
  config:
    activate:
      on-profile: local-hyewon

  datasource:
    url: jdbc:mysql://localhost:3306/llmeta
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql
      mode: always

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  websecurity:
    debug: true

logging:
  level:
    org:
      springframework:
        security: DEBUG