spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://llmeta-database.cxn9oybwo8mo.ap-northeast-2.rds.amazonaws.com:3306/llmeta?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: admin
    password: llmeta2024
    driver-class-name: com.mysql.cj.jdbc.Driver