spring:
  profiles:
    include: private

# s3
cloud:
  aws:
    credentials:
      access-key: ${{ secrets.AWS_ACCESS_KEY }}
      secret-key: ${{ secrets.AWS_SECRET_KEY }}

    s3:
      bucket: llmeta-be-bucket

    stack.auto: false
    region.static: ap-northeast-2